apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: storage-service-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20


