apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-configmap
  namespace: backend
data:
  PORT: "3000"
  DB_HOST: "fake-db-host"
  DB_PORT: "5432"
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_NAME: "authdb"
