apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: main-api-httproute
  namespace: backend
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - "main-api.internal"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: main-api
          port: 80
