apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: backend
  labels:
    app: main-api
spec:
  selector:
    app: main-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
