apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-api-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
