apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: backend
spec:
  gatewayClassName: app-gatewayclass
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: main-api.internal
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: mkcert
      allowedRoutes:
        namespaces:
          from: Same
